[package]
name = "simple-solana-geyser-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-geyser-plugin-interface = "=1.18.17"
solana-sdk = "=1.18.17"
solana-logger = "=1.18.26"
log = "0.4.22"
